// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzzasndrtdqeubtvmdio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6emFzbmRydGRxZXVidHZtZGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTgzNzYsImV4cCI6MjA3Mjk5NDM3Nn0.-1Il1QyHws2Ln0_pIF_56a6iP4Bdw9vGE8h-wcLrz48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});